name: Parkplatz Checker

on:
  schedule:
    # 07:00 UTC = 08:00 Uhr Winterzeit (Deutschland)
    - cron: '0 7 * * *'
  workflow_dispatch: # Für manuellen Start

jobs:
  run-check:
    runs-on: ubuntu-latest
    steps:
      - name: Code laden
        uses: actions/checkout@v3

      - name: Python einrichten
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Installieren
        # WICHTIG: Hier muss 'pytz' mit dabei stehen!
        run: pip install requests beautifulsoup4 pytz

      - name: Skript ausführen
        run: python main.py
