name: Parkplatz Checker

on:
  schedule:
    # 07:00 UTC = 08:00 Uhr Winterzeit (Deutschland)
    # Im Sommer ist das dann 09:00 Uhr.
    - cron: '0 7 * * *'
  workflow_dispatch:

jobs:
  run-check:
    runs-on: ubuntu-latest
    steps:
      - name: Code laden
        uses: actions/checkout@v3

      - name: Python einrichten
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Installieren
        run: pip install requests beautifulsoup4

      - name: Starten
        run: python main.py

      - name: Installieren
        run: pip install requests beautifulsoup4 pytz
